// List Starship
export const LIST_STARSHIP_REQUEST = 'LIST_STARSHIP_REQUEST'
export const SEARCH_STARSHIP_REQUEST = 'SEARCH_STARSHIP_REQUEST'
export const LIST_STARSHIP_SUCCESS = 'LIST_STARSHIP_SUCCESS'
export const LIST_STARSHIP_FAILURE = 'LIST_STARSHIP_FAILURE'
export const SCROLL_STARSHIP_REQUEST = 'SCROLL_STARSHIP_REQUEST'
export const SCROLL_STARSHIP_SUCCESS = 'SCROLL_STARSHIP_SUCCESS'

// List Starship
export const DETAIL_STARSHIP_REQUEST = 'DETAIL_STARSHIP_REQUEST'
export const DETAIL_STARSHIP_SUCCESS = 'DETAIL_STARSHIP_SUCCESS'
export const DETAIL_STARSHIP_FAILURE = 'DETAIL_STARSHIP_FAILURE'
